data_path: examples/sample_data/pdf
google_drive_ids: []
previous_results: null

dispatcher_config:
  output_path: examples/process/outputs/
  use_fast_processors: false
  distributed: false
  dashboard_backend_url: null
  extract_images: false
  scheduler_file: null

  process_batch_sizes:
    - processor_name: PDFProcessor
      batch_size: 100
    - processor_name: TXTProcessor
      batch_size: 100
    - processor_name: MarkdownProcessor
      batch_size: 50
    - processor_name: MediaProcessor
      batch_size: 20
    - processor_name: HTMLProcessor
      batch_size: 50
    - processor_name: DOCXProcessor
      batch_size: 50
    - processor_name: SpreadsheetProcessor
      batch_size: 50
    - processor_name: PPTXProcessor
      batch_size: 50
    - processor_name: EMLProcessor
      batch_size: 50
    - processor_name: URLProcessor
      batch_size: 20
