name: Build2
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
          pip install ".[all]"
          pip install dask distributed

      - name: Run PDF Process
        run: |
          python -m mmore process --config-file examples/process/test2.yaml

      - name: Run Index
        run: |
          python -m mmore index --config-file examples/index/config.yaml

      - name: Package Files
        run: |
          tar -czf - . | split -b 2000M - mmore-output.tar.gz

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: mmore-output.tar.gz*
          tag_name: v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
